 root = "."
 tmp_dir = "build"
 
 [build]
 	bin = "./build/main"
 	cmd = "templ generate && go build -o ./build/main cmd/main.go"
 	delay = 1000
 	exclude_dir = ["static", "node_modules", "build"]
 	exclude_regex = [".*_templ.go"]
 	exclude_unchanged = false
 	follow_symlink = false
 	include_ext = ["go", "tpl", "tmpl", "templ", "html"]
 	kill_delay = "0s"
 	log = "build-errors.log"
 	send_interrupt = false
 	stop_on_error = true
 
 [color]
 	build = "yellow"
 	main = "magenta"
 	runner = "green"
 	watcher = "cyan"
 
 [log]
 	time = false
 
 [misc]
 	clean_on_exit = true
 