// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.908
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "kristin-gerber/internal/model"

func HomePage(data model.HomeData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><div class=\"w-full bg-[#C9D0DF] py-24\"><div class=\"container mx-auto max-w-[1000px] w-full\"><div class=\"grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-10 mx-12\"><div class=\"md:col-span-1 flex justify-center items-center w-[50%] md:w-full mx-auto\"><div class=\"relative w-full aspect-square max-w-[300px]\"><img src=\"/static/images/home/kristin.jpg\" alt=\"Kristin Gerber\" class=\"w-full h-full object-contain border-4 border-white shadow-lg shadow-gray-500\"></div></div><div class=\"md:col-span-2 lg:col-span-3 text-left tracking-wide\"><p class=\"whitespace-pre-line\"><b>Kristin Gerber</b> is a visual artist with a distinguished international career spanning over sixty years. Her practice, encompassing painting, etching, and visual objects, has been developed across Santiago de Chile, Paris, Munich, Berlin, London, and New York.<br><br>Her extensive training includes studies at the Escuela de Bellas Artes in Chile, the École Nationale des Beaux Arts in Paris, and specialized work in etching at the renowned Atelier 17. Gerber's work has been featured in significant exhibitions like the Paris Biennale and at venues in New York, Helsinki, and Berlin, supported by prestigious scholarships from the British Council and the DAAD.<br><br>Complementing her artistic output, Gerber has been a dedicated educator since 1970, teaching design and jewelry making in Berlin and serving as a guest lecturer at the University of Arts Berlin. Her career reflects a sustained commitment to both creating and teaching art on a global stage.</p></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = HomeGallery(data).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
