name: Deploy Production
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    concurrency: deploy-production
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a kristin-gerber-prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}