name: Deploy Staging
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    concurrency: deploy-staging
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a kristin-gerber-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
